<?php
// $unionarray = array('SAG', 'SAG-Eligible', 'AEA', 'AFTRA', 'AGVA', 'Non-Union');
$unionarray = array('SAG-AFTRA', 'SAG-Eligible', 'AEA', 'AGVA', 'Non-Union');

$voicearray = array('No Singing Experience', 'Soprano', 'Mezzo-Soprano', 'Contralto', 'Tenor', 'Baritone', 'Bass-Baritone', 'Bass');

$locationarray = array('New York', 'California', 'DC', 'Nashville', 'Florida', 'Mid-Atlantic', 'Southeast', 'Northwest', 'Pacific Coastal');

$required_material_Ary = array('Photos', 'Reel', 'Self Tapes', 'Resume', 'Note');

// $castingarray = array('print', 'commercial', 'fashion', 'legit/acting', 'hosting/reality', 'promotional');
// $jobtypearray = array('Print', 'TV', 'Film', 'Commercial', 'Web', 'Industrial', 'Psa', 'Stage', 'Event', 'Promotional', 'Other');

$jobtypearray = array('Print', 'Commercial', 'Editorial', 'Runway', 'Test shoot', 'Fashion', 'TV', 'Film', 'Stage/Theater', 'Hosting', 'Web/Internet', 'PSA', 'Reality', 'Industrial', 'Event', 'Fit', 'Parts', 'Promotional', 'Voice Over', 'Music Video', 'Promo', 'Short Film');
sort($jobtypearray);
$castingarray = $jobtypearray;

// talent listing
$castingarray = array('Commercial', 
                      'Infomercial', 
                      'Spec', 
                      'Video Shoot', 
                      'Editorial', 
                      'Event', 
                      'Fashion', 
                      'Feature Film', 
                      'Short Film', 
                      'Independent Film', 
                      'Live Presentation', 
                      'Fit', 
                      'Hosting', 
                      'Industrial', 
                      'Music Video', 
                      'PSA', 
                      'Parts', 
                      'Print', 
                      'Promo', 
                      'Trailer', 
                      'Episodic', 
                      'Reality TV',
                      'Student Project',
                      'Pilot',
                      'Documentary',
                      'Social Media',
                      'Web Series',
                      'Promotional',
                      'Reality',
                      'Runway',
                      'Stage/Theater',
                      'TV',
                      'Test shoot',
                      'Voice Over',
                      'Web/Internet',
                      'Other'
                    );


$castingicons = array('Print'=>'PrintEditorialFit.jpg',
						'Commercial'=>'CommercialIndustrial.jpg',
						'Editorial'=>'PrintEditorialFit.jpg', 
						'Runway'=>'RunwayFashionEventPromotional.jpg', 
						'Test shoot'=>'TestShootParts.jpg', 
						'Fashion'=>'RunwayFashionEventPromotional.jpg', 
						'TV'=>'TVReality.jpg', 
						'Film'=>'FilmOTHER.jpg', 
						'Stage/Theater'=>'StageTheatre.jpg', 
						'Hosting'=>'HostingPromo.jpg', 
						'Web/Internet'=>'WebInternet.jpg', 
						'PSA'=>'PSA.jpg', 
						'Reality'=>'TVReality.jpg', 
						'Industrial'=>'CommercialIndustrial.jpg', 
						'Event'=>'RunwayFashionEventPromotional.jpg', 
						'Fit'=>'PrintEditorialFit.jpg', 
						'Parts'=>'TestShootParts.jpg', 
						'Promotional'=>'RunwayFashionEventPromotional.jpg', 
						'Voice Over'=>'Voiceover.jpg', 
						'Music Video'=>'MusicVideo.jpg', 
						'Promo'=>'HostingPromo.jpg',
						'Short Film'=>'FilmOTHER.jpg');
						
$bracups = array(
        // ''=>'',
				'10'=>'AA',
				'20'=>'A',
				'30'=>'B',
				'40'=>'C',
				'50'=>'D',
				'60'=>'DD',
				'70'=>'DDD/E/F',
				'80'=>'DDDD/F/G',
				'90'=>'G/H/J',
				'100'=>'I/J/K',
				'110'=>'J',
				'120'=>'K',
				'130'=>'L',
				'140'=>'M',
				'150'=>'N');

// $jobunionarray = array('SAG', 'AEA/Equity', 'AFTRA', 'AGVA', 'Non-Union', 'Non-Specified/Open to All', 'Other');
$jobunionarray = array('SAG-AFTRA', 'AEA/Equity', 'AGVA', 'Non-Union', 'Non-Specified/Open to All', 'Other');

// $ethnicityarray = array('Asian', 'Caucasian', 'African-American/African', 'Hispanic', 'Middle Eastern/North African', 'South Asian/Indian', 'Mixed Ethnicity', 'Other');
$ethnicityarray = array('African American', 'Asian', 'Caucasian', 'Hispanic', 'Middle Eastern', 'Multi-Ethnic', 'Native American', 'East Indian', 'Pacific Islander', 'Ambiguous');

$malearray = array('height', 'waist', 'inseam', 'suit', 'shirt', 'neck',  'inseam', 'shoe', 'hair', 'eyes', 'weight');
$femalearray = array('height', 'bust', 'cup', 'inseam', 'waist', 'hips', 'shoe', 'dress', 'hair', 'eyes', 'weight');

$maleArray_new = array('waist', 'inseam', 'suit', 'shirt', 'neck',  'inseam', 'shoe');
$femaleArray_new = array('bust', 'cup', 'inseam', 'waist', 'hips', 'shoe', 'dress');

$experiencearray = array('1'=>'New Face', '2'=>'Experienced', '3'=>'Professional' );
$experienceimages = array('1'=>'exp_new_faces', '2'=>'exp_experienced', '3'=>'exp_professional');
$experiencecolors = array('1'=>'#0000FF', '2'=>'#FF0000', '3'=>'#000000');

$categoryarray_1 = array('fashion', 'commercial print', 'actors/legit', 'alternative', 'beauty', 'commercial', 'fit models',
						 'dancers', 'singers', 'plus size', 'fitness', 'extras', 'theater', 'runway', 'parts', 'testshoot', 'kids - via parent/manager','teens - via parent/manager', 'voice over', 'music video', 'promo', 'other');
$categoryarray_2 = array('super plus', 'tall', 'little', 'muscles/contortionists', 'senior', 'tattooed/pierced', 'twins/multiples',
						'extreme/rare', 'transgender/drag');
$haircolorarray = array('Black', 'Auburn', 'Brown', 'Light Brown', 'Blond', 'Strawberry Blond', 'Platinum', 'Grey', 'Red', 'Blue', 'Green', 'Purple', 'Salt &amp; Pepper', 'Multi-color', 'Bald/None');
$eyecolorarray = array('Black', 'Brown', 'Hazel', 'Grey', 'Blue', 'Green');
$eyeShapeArray = array('Slant','Oval','Pear');

$privacylevels = array('lastname' => array('nobody' => 'Nobody', 'clients' => 'Clients Only', 'friends' => 'Friends Only', 'clientsfriends' => 'Clients and Friends Only', 'everyone' => 'Everyone'),
						'bio' => array('clients' => 'Clients Only', 'clientsfriends' => 'Clients and Friends Only', 'everyone' => 'Everyone'),
						'links' => array('clients' => 'Clients Only', 'clientsfriends' => 'Clients and Friends Only', 'everyone' => 'Everyone'),
						'skills' => array('clients' => 'Clients Only', 'clientsfriends' => 'Clients and Friends Only', 'everyone' => 'Everyone'),
												);
$privacylabels = array( 'lastname' => 'Last Name', 'bio' => 'Biography', 'links' => 'Links', 'skills' => 'Skills');

$countryarray = array(
  "GB" => "United Kingdom",
  "US" => "United States",
  "AF" => "Afghanistan",
  "AL" => "Albania",
  "DZ" => "Algeria",
  "AS" => "American Samoa",
  "AD" => "Andorra",
  "AO" => "Angola",
  "AI" => "Anguilla",
  "AQ" => "Antarctica",
  "AG" => "Antigua And Barbuda",
  "AR" => "Argentina",
  "AM" => "Armenia",
  "AW" => "Aruba",
  "AU" => "Australia",
  "AT" => "Austria",
  "AZ" => "Azerbaijan",
  "BS" => "Bahamas",
  "BH" => "Bahrain",
  "BD" => "Bangladesh",
  "BB" => "Barbados",
  "BY" => "Belarus",
  "BE" => "Belgium",
  "BZ" => "Belize",
  "BJ" => "Benin",
  "BM" => "Bermuda",
  "BT" => "Bhutan",
  "BO" => "Bolivia",
  "BA" => "Bosnia And Herzegowina",
  "BW" => "Botswana",
  "BV" => "Bouvet Island",
  "BR" => "Brazil",
  "IO" => "British Indian Ocean Territory",
  "BN" => "Brunei Darussalam",
  "BG" => "Bulgaria",
  "BF" => "Burkina Faso",
  "BI" => "Burundi",
  "KH" => "Cambodia",
  "CM" => "Cameroon",
  "CA" => "Canada",
  "CV" => "Cape Verde",
  "KY" => "Cayman Islands",
  "CF" => "Central African Republic",
  "TD" => "Chad",
  "CL" => "Chile",
  "CN" => "China",
  "CX" => "Christmas Island",
  "CC" => "Cocos (Keeling) Islands",
  "CO" => "Colombia",
  "KM" => "Comoros",
  "CG" => "Congo",
  "CD" => "Congo, The Democratic Republic Of The",
  "CK" => "Cook Islands",
  "CR" => "Costa Rica",
  "CI" => "Cote D'Ivoire",
  "HR" => "Croatia (Local Name: Hrvatska)",
  "CU" => "Cuba",
  "CY" => "Cyprus",
  "CZ" => "Czech Republic",
  "DK" => "Denmark",
  "DJ" => "Djibouti",
  "DM" => "Dominica",
  "DO" => "Dominican Republic",
  "TP" => "East Timor",
  "EC" => "Ecuador",
  "EG" => "Egypt",
  "SV" => "El Salvador",
  "GQ" => "Equatorial Guinea",
  "ER" => "Eritrea",
  "EE" => "Estonia",
  "ET" => "Ethiopia",
  "FK" => "Falkland Islands (Malvinas)",
  "FO" => "Faroe Islands",
  "FJ" => "Fiji",
  "FI" => "Finland",
  "FR" => "France",
  "FX" => "France, Metropolitan",
  "GF" => "French Guiana",
  "PF" => "French Polynesia",
  "TF" => "French Southern Territories",
  "GA" => "Gabon",
  "GM" => "Gambia",
  "GE" => "Georgia",
  "DE" => "Germany",
  "GH" => "Ghana",
  "GI" => "Gibraltar",
  "GR" => "Greece",
  "GL" => "Greenland",
  "GD" => "Grenada",
  "GP" => "Guadeloupe",
  "GU" => "Guam",
  "GT" => "Guatemala",
  "GN" => "Guinea",
  "GW" => "Guinea-Bissau",
  "GY" => "Guyana",
  "HT" => "Haiti",
  "HM" => "Heard And Mc Donald Islands",
  "VA" => "Holy See (Vatican City State)",
  "HN" => "Honduras",
  "HK" => "Hong Kong",
  "HU" => "Hungary",
  "IS" => "Iceland",
  "IN" => "India",
  "ID" => "Indonesia",
  "IR" => "Iran (Islamic Republic Of)",
  "IQ" => "Iraq",
  "IE" => "Ireland",
  "IL" => "Israel",
  "IT" => "Italy",
  "JM" => "Jamaica",
  "JP" => "Japan",
  "JO" => "Jordan",
  "KZ" => "Kazakhstan",
  "KE" => "Kenya",
  "KI" => "Kiribati",
  "KP" => "Korea, Democratic People's Republic Of",
  "KR" => "Korea, Republic Of",
  "KW" => "Kuwait",
  "KG" => "Kyrgyzstan",
  "LA" => "Lao People's Democratic Republic",
  "LV" => "Latvia",
  "LB" => "Lebanon",
  "LS" => "Lesotho",
  "LR" => "Liberia",
  "LY" => "Libyan Arab Jamahiriya",
  "LI" => "Liechtenstein",
  "LT" => "Lithuania",
  "LU" => "Luxembourg",
  "MO" => "Macau",
  "MK" => "Macedonia, Former Yugoslav Republic Of",
  "MG" => "Madagascar",
  "MW" => "Malawi",
  "MY" => "Malaysia",
  "MV" => "Maldives",
  "ML" => "Mali",
  "MT" => "Malta",
  "MH" => "Marshall Islands",
  "MQ" => "Martinique",
  "MR" => "Mauritania",
  "MU" => "Mauritius",
  "YT" => "Mayotte",
  "MX" => "Mexico",
  "FM" => "Micronesia, Federated States Of",
  "MD" => "Moldova, Republic Of",
  "MC" => "Monaco",
  "MN" => "Mongolia",
  "MS" => "Montserrat",
  "MA" => "Morocco",
  "MZ" => "Mozambique",
  "MM" => "Myanmar",
  "NA" => "Namibia",
  "NR" => "Nauru",
  "NP" => "Nepal",
  "NL" => "Netherlands",
  "AN" => "Netherlands Antilles",
  "NC" => "New Caledonia",
  "NZ" => "New Zealand",
  "NI" => "Nicaragua",
  "NE" => "Niger",
  "NG" => "Nigeria",
  "NU" => "Niue",
  "NF" => "Norfolk Island",
  "MP" => "Northern Mariana Islands",
  "NO" => "Norway",
  "OM" => "Oman",
  "PK" => "Pakistan",
  "PW" => "Palau",
  "PA" => "Panama",
  "PG" => "Papua New Guinea",
  "PY" => "Paraguay",
  "PE" => "Peru",
  "PH" => "Philippines",
  "PN" => "Pitcairn",
  "PL" => "Poland",
  "PT" => "Portugal",
  "PR" => "Puerto Rico",
  "QA" => "Qatar",
  "RE" => "Reunion",
  "RO" => "Romania",
  "RU" => "Russian Federation",
  "RW" => "Rwanda",
  "KN" => "Saint Kitts And Nevis",
  "LC" => "Saint Lucia",
  "VC" => "Saint Vincent And The Grenadines",
  "WS" => "Samoa",
  "SM" => "San Marino",
  "ST" => "Sao Tome And Principe",
  "SA" => "Saudi Arabia",
  "SN" => "Senegal",
  "SC" => "Seychelles",
  "SL" => "Sierra Leone",
  "SG" => "Singapore",
  "SK" => "Slovakia (Slovak Republic)",
  "SI" => "Slovenia",
  "SB" => "Solomon Islands",
  "SO" => "Somalia",
  "ZA" => "South Africa",
  "GS" => "South Georgia, South Sandwich Islands",
  "ES" => "Spain",
  "LK" => "Sri Lanka",
  "SH" => "St. Helena",
  "PM" => "St. Pierre And Miquelon",
  "SD" => "Sudan",
  "SR" => "Suriname",
  "SJ" => "Svalbard And Jan Mayen Islands",
  "SZ" => "Swaziland",
  "SE" => "Sweden",
  "CH" => "Switzerland",
  "SY" => "Syrian Arab Republic",
  "TW" => "Taiwan",
  "TJ" => "Tajikistan",
  "TZ" => "Tanzania, United Republic Of",
  "TH" => "Thailand",
  "TG" => "Togo",
  "TK" => "Tokelau",
  "TO" => "Tonga",
  "TT" => "Trinidad And Tobago",
  "TN" => "Tunisia",
  "TR" => "Turkey",
  "TM" => "Turkmenistan",
  "TC" => "Turks And Caicos Islands",
  "TV" => "Tuvalu",
  "UG" => "Uganda",
  "UA" => "Ukraine",
  "AE" => "United Arab Emirates",
  "UM" => "United States Minor Outlying Islands",
  "UY" => "Uruguay",
  "UZ" => "Uzbekistan",
  "VU" => "Vanuatu",
  "VE" => "Venezuela",
  "VN" => "Viet Nam",
  "VG" => "Virgin Islands (British)",
  "VI" => "Virgin Islands (U.S.)",
  "WF" => "Wallis And Futuna Islands",
  "EH" => "Western Sahara",
  "YE" => "Yemen",
  "YU" => "Yugoslavia",
  "ZM" => "Zambia",
  "ZW" => "Zimbabwe"
);

$stateList['US'] = array(
    'AL'        => 'Alabama',
    'AK'        => 'Alaska',
    'AZ'        => 'Arizona',
    'AR'        => 'Arkansas',
    'CA'        => 'California',
    'CO'        => 'Colorado',
    'CT'        => 'Connecticut',
	'DC'		=> 'District of Columbia',
    'DE'        => 'Delaware',
    'FL'        => 'Florida',
    'GA'        => 'Georgia',
    'HI'        => 'Hawaii',
    'ID'        => 'Idaho',
    'IL'        => 'Illinois',
    'IN'        => 'Indiana',
    'IA'        => 'Iowa',
    'KS'        => 'Kansas',
    'KY'        => 'Kentucky',
    'LA'        => 'Louisiana',
    'ME'        => 'Maine',
    'MD'        => 'Maryland',
    'MA'        => 'Massachusetts',
    'MI'        => 'Michigan',
    'MN'        => 'Minnesota',
    'MS'        => 'Mississippi',
    'MO'        => 'Missouri',
    'MT'        => 'Montana',
    'NE'        => 'Nebraska',
    'NV'        => 'Nevada',
    'NH'        => 'New Hampshire',
    'NJ'        => 'New Jersey',
    'NM'        => 'New Mexico',
    'NY'        => 'New York',
    'NC'        => 'North Carolina',
    'ND'        => 'North Dakota',
    'OH'        => 'Ohio',
    'OK'        => 'Oklahoma',
    'OR'        => 'Oregon',
    'PA'        => 'Pennsylvania',
	'PR'        => 'Puerto Rico',
    'RI'        => 'Rhode Island',
    'SC'        => 'South Carolina',
    'SD'        => 'South Dakota',
    'TN'        => 'Tennessee',
    'TX'        => 'Texas',
    'UT'        => 'Utah',
    'VT'        => 'Vermont',
    'VA'        => 'Virginia',
    'WA'        => 'Washington',
    'WV'        => 'West Virginia',
    'WI'        => 'Wisconsin',
    'WY'        => 'Wyoming');
    
    $profile_pic_thumb = array('25'=>'25','50'=>'50','84'=>'84','128'=>'128');
    $headshot_thumb = array('300'=>'300');
    // $card_thumb = array('25'=>'25','80'=>'80','300'=>'300');
    $portfolio_thumb = $card_thumb = array('25'=>'25','50'=>'50','80'=>'80','128'=>'128','300'=>'300');

    // talent manager
    $reg_city_tm_ary = array("Florida","Los Angeles","New York");
    $how_many_talent_ary = array("10-20","21-50","50+");
    $company_in_business_ary = array("0-20","20+");
    $type_of_project_ary = array("Commercial", "Print","Theatrical","Film", "Voice over", "Singing", "Special Skills");

    $recaptcha_site_key = "6LfYBqwZAAAAAJ4UR1CVEq08GWhHwr723ZrXQ4lh";
    $recaptcha_secret_key = "6LfYBqwZAAAAACkmAhafG1Bul4_ae6xOnZrmB4CT";

    // casting director
    $avg_no_of_pro_client = array("1-4","5-9","10+");
    $how_did_hear_about_us = array("Agency Employee","Facebook","Google","Twitter","Instagram","Referred by casting director","Ad Agency","Production Company","Received a personal invite","Other");

    $Primary_casting_region = array('New York', 'California', 'Florida', 'DC', 'Nashville', 'Mid-Atlantic', 'Southeast', 'Northwest', 'Pacific', 'Nationwide');
?>
